import { country, category } from './types';

export const countryNames: Record<country, string> = {
  ar: 'Argentina',
  au: 'Australia',
  at: 'Austria',
  be: 'Belgium',
  br: 'Brazil',
  bg: 'Bulgaria',
  ca: 'Canada',
  cn: 'China',
  co: 'Colombia',
  cu: 'Cuba',
  cz: 'Czech Republic',
  eg: 'Egypt',
  fr: 'France',
  de: 'Germany',
  gb: 'Great Britain',
  gr: 'Greece',
  hk: 'Hong-Kong',
  hu: 'Hungary',
  in: 'India',
  id: 'Indonesia',
  ie: 'Ireland',
  il: 'Israel',
  it: 'Italy',
  jp: 'Japan',
  kr: 'Korea',
  lv: 'Latvia',
  lt: 'Lithuania',
  my: 'Malaysia',
  mx: 'Mexico',
  ma: 'Morocco',
  nl: 'Netherlands',
  nz: 'New Zealand',
  ng: 'Nigeria',
  no: 'Norway',
  ph: 'Philippines',
  pl: 'Poland',
  pt: 'Portugal',
  ro: 'Romania',
  ru: 'Russia',
  rs: 'Serbia',
  ch: 'Switzerland',
  sa: 'Saudi Arabia',
  sg: 'Singapure',
  sk: 'Slovakia',
  si: 'Slovenia',
  za: 'South Africa',
  se: 'Sweden',
  tw: 'Taiwan',
  th: 'Thailand',
  tr: 'Turkey',
  ua: 'Ukraine',
  ae: 'United Arab Emirates',
  us: 'United States',
  ve: 'Venezuela',
};

export const countryArr: country[] = [
  'ar',
  'au',
  'at',
  'be',
  'br',
  'bg',
  'ca',
  'cn',
  'co',
  'cu',
  'cz',
  'eg',
  'fr',
  'de',
  'gb',
  'gr',
  'hk',
  'hu',
  'in',
  'id',
  'ie',
  'il',
  'it',
  'jp',
  'kr',
  'lv',
  'lt',
  'my',
  'mx',
  'ma',
  'nl',
  'nz',
  'ng',
  'no',
  'ph',
  'pl',
  'pt',
  'ro',
  'ru',
  'rs',
  'ch',
  'sa',
  'sg',
  'sk',
  'si',
  'za',
  'se',
  'tw',
  'th',
  'tr',
  'ua',
  'ae',
  'us',
  've',
];

export const categoryArr: category[] = [
  'business',
  'entertainment',
  'general',
  'health',
  'science',
  'sports',
  'technology',
];

export const categoryNames: Record<category, string> = {
  business: 'Business',
  entertainment: 'Entertainment',
  general: 'General',
  health: 'Health',
  science: 'Science',
  sports: 'Sports',
  technology: 'Technology'
};
